name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ShaleSeg: dataset"
  comment: "The first deep-learning dataset and models for practical fracture segmentation of large-scale-shale CT images"
  url: "http://www.geophys.ac.cn/ArticleData/20231023ShaleSeg.zip"
  file_name: "Shaleseg.zip"
  piece_size: 24 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
